### ISSUE TITLE
Unable to replicate train brightening

### ISSUE THREAD

**Issue by gkagkos** [daooshee/HLA-Face-Code#10]
Hi, thanks for your nice work. I am trying to replicate the results from the train_brightening procedure, however, I am unable to recreate the visual results of the enhanced data that you are providing. My enhanced saved images are much more noisy.

**Comment by gkagkos** [comment]
Update: I am also **unable to recreate the data** you are providing even by running the low_light_test.py **with your model (Illumination_Enhancer.pth)**

**Comment by gkagkos** [comment]
@daooshee I would appreciate a reply. Thank you!

**Comment by daooshee** [comment]
Hi, gkagkos. It's strange that even `low_light_test.py` with `Illumination_Enhancer.pth` does not work. Could you provide more details about your implementation?

**Comment by gkagkos** [comment]
The implementation is a copy paste of yours. I am running the train_brightening file and then I am running the low_light_test file with the trained network. The results that I am receiving are not the same with the ones you are providing. Specifically the results that you are providing are smoother than the results from training. You can have a look [here](https://drive.google.com/drive/folders/1yZQiFdMuL2FHnsmOTrS9jfqkzm7Wy1iq?usp=sharing).

**Comment by gkagkos** [comment]
Hi again, @daooshee did you check the output that I upload ?

**Comment by daooshee** [comment]
Hi, sorry that I have some DDLs these days, so the reply might not be in time. `img_6k_provided.png` and  `img_6k_trained.png` seem basically correct.
I also upload an original-enhanced pair: https://drive.google.com/drive/folders/1UgYjl1opnDDe_sB_tYuzQJcO8hKJHvEl?usp=sharing, which might be helpful to check the implementation.

**Comment by daooshee** [comment]
Since train_brightening has some randomness, so the result might not be exactly the same each time training. I think `img_6k_trained.png` basically works. You can also check more checkpoints that train_brightening saves to find a better one.

**Comment by gkagkos** [comment]
Thanks for the reply and for the clarifications. Closing the issue.
