### ISSUE TITLE
UG2+ Track1.2

### ISSUE THREAD

**Issue by zhebawomenjiuyaochangshenle** [daooshee/HLA-Face-Code#15]
I want to test the effect on CodaLab, but prompt Submission upload has had been disabled. See the new instance at: https://codalab.lisn.upsaclay.fr/. I can't find the same item in the new site, how do I test it? Thank you

**Comment by daooshee** [comment]
Hi, this is due to that CodaLab changed its server.
According to CodaLab, "This server is not longer accepting new challenges not new submissions to old challenges."
We will try to rebuild the upload platform as soon as possible. When the new platform is ready, I'll contact you. Thank you for reporting this problem.

**Comment by zhebawomenjiuyaochangshenle** [comment]
Ok. Thank you very much.

**Comment by daooshee** [comment]
Hi, the new CodaLab site is: https://codalab.lisn.upsaclay.fr/competitions/8494?secret_key=cae604ef-4bd6-4b3d-88d9-2df85f91ea1c.

**Comment by kairenchen123** [comment]
What is the format of the submission file for this competition? Is it.CSV format?
Each image is listed in.csv as
1.png
111 222 222 333 0.999
222 333 444 555 0.888
2.png
...

**Comment by kairenchen123** [comment]
> I want to test the effect on CodaLab, but prompt Submission upload has had been disabled. See the new instance at: https://codalab.lisn.upsaclay.fr/. I can't find the same item in the new site, how do I test it? Thank you

Hello, what should be the format of the submitted result file?

**Comment by daooshee** [comment]
Hi, you may refer to [this file](https://drive.google.com/file/d/1s-QjefTpN8zXQJAuamCZ35snqrG3T5kj/view?usp=sharing), which produces an mAP score of 0.459109.

**Comment by kairenchen123** [comment]
> Hi, you may refer to [this file](https://drive.google.com/file/d/1s-QjefTpN8zXQJAuamCZ35snqrG3T5kj/view?usp=sharing), which produces an mAP score of 0.459109.
Do I submit the compressed txt file to CodaLab?

**Comment by kairenchen123** [comment]
> Hi, you may refer to [this file](https://drive.google.com/file/d/1s-QjefTpN8zXQJAuamCZ35snqrG3T5kj/view?usp=sharing), which produces an mAP score of 0.459109.

thank you your reply
