### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by xuebaliang** [daooshee/HLA-Face-Code#3]
Hello, when I run "python train.py --multigpu" with 4 GPUs in pytorch1.7, I meet the following error,
Traceback (most recent call last):
  File "train.py", line 403, in <module>
    loss.backward()
  File "/root/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([2, 64, 4, 4], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(64, 64, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()
ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f2944305e20
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2, 64, 4, 4, 
    strideA = 1024, 16, 4, 1, 
output: TensorDescriptor 0x7f2944321900
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2, 64, 4, 4, 
    strideA = 1024, 16, 4, 1, 
weight: FilterDescriptor 0x7f29442f7740
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 64, 64, 3, 3, 
Pointer addresses: 
    input: 0x7f267b5fd400
    output: 0x7f267d77ba00
    weight: 0x7f27d7b2f600
Additional pointer addresses: 
    grad_output: 0x7f267d77ba00
    grad_weight: 0x7f27d7b2f600
Backward filter algorithm: 3

Have you ever encountered this bug?

**Comment by daooshee** [comment]
Hi, sorry that I haven't encountered this bug. For training, I use PyTorch 1.6.0. Have you tried lower PyTorch versions?
