### ISSUE TITLE
How to calculate the metrics?

### ISSUE THREAD

**Issue by JunrQ** [daooshee/HLA-Face-Code#4]
Hello, amazing work, thanks for sharing the code, I have one question

It seems the `test.py` just save the detection results in a file, can you please tell me how to mAP value?

**Comment by daooshee** [comment]
Hi, you can test the result on [codalab](https://competitions.codalab.org/competitions/32499#participate).

**Comment by JunrQ** [comment]
Thank you for the reply, may I ask one more question, 

How to get the data to draw the PR curve in your paper, since it requires detection results for all the involved method.

**Comment by daooshee** [comment]
I draw the PR curve by the [official evaluation tool of DARK FACE](https://github.com/Ir1d/DARKFACE_eval_tools). It can draw PR curves based on the detection results (.txt files). As for the detection results, we just run the methods and save their prediction.

**Comment by yanqinJiang** [comment]
It seems that the download link in [codalab](https://competitions.codalab.org/competitions/32499#participatel) doesn't work anymore. Is the submission still allowed? And could you please share the test data with me? thx.

**Comment by daooshee** [comment]
Submission is still allowed on CodaLab~ The invalid link will be updated recently.
