### ISSUE TITLE
why need  the file ./dataset/mf_dsfd_dark_face_train.txt

### ISSUE THREAD

**Issue by ShangGL123** [daooshee/HLA-Face-Code#7]
First of all, thank you for your answer .I don't understand why need use [MF] + [DSFD]to detect the faces in DARK FACE

**Comment by daooshee** [comment]
Thank you for your interest in our work.

HLA-Face needs to crop patches for the jigsaw self-supervised task. However, if there is no object in the patch (for example, if this patch is about a pure black night sky), there would be no answer for the jigsaw task. To avoid this problem, I first detect faces using MF+DSFD. MF+DSFD may predict wrong faces, but its prediction is mainly in the foreground, which can avoid background like night skies. Using other methods should also be OK, such as Zero-DCE or Small Hard Face.

I haven't conducted an ablation study about this point. Maybe pure black night key patches are just some kind of noise and do not influence the training process.

**Comment by ShangGL123** [comment]
In other words, instead of dividing the whole picture into 3X3, the main foreground part is extracted and divided into 3x3 for train?

**Comment by changjiahao** [comment]
> In other words, instead of dividing the whole picture into 3X3, the main foreground part is extracted and divided into 3x3 for train?
