### ISSUE TITLE
where is the  class Detect defined?

### ISSUE THREAD

**Issue by ShangGL123** [daooshee/HLA-Face-Code#8]

**Comment by daooshee** [comment]
Hi,  the class is defined here: [test_code/layers/functions/detection.py](https://github.com/daooshee/HLA-Face-Code/blob/2b5737e206741378dcc599ee3fd5b3c6198c8705/test_code/layers/functions/detection.py#L13)

**Comment by ShangGL123** [comment]
> _No description provided._



> Hi, the class is defined here: [test_code/layers/functions/detection.py](https://github.com/daooshee/HLA-Face-Code/blob/2b5737e206741378dcc599ee3fd5b3c6198c8705/test_code/layers/functions/detection.py#L13)

thanks haha I just found it
