### ISSUE TITLE
darkface测试集

### ISSUE THREAD

**Issue by guohuanguohuan** [daooshee/HLA-Face-Code#9]
你好，官网无法下载darkface测试集的标签，请问您有测试集的标签吗？麻烦分享一下呗！

**Comment by daooshee** [comment]
Hi, sorry that I also do not have the labels of the testing set. But you can evaluate the performance on [CodaLab](https://competitions.codalab.org/competitions/32499#participate-submit_results).

**Comment by guohuanguohuan** [comment]
谢谢
